const ADD_PERSON_SUCCESS = 'ADD_PERSON_SUCCESS';
const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';
const GET_PEOPLE = 'GET_PEOPLE';
const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';

export {
    ADD_PERSON_SUCCESS,
    UPDATE_PERSON_SUCCESS,
    GET_PEOPLE,
    DELETE_PERSON_SUCCESS
}